### ISSUE TITLE
Script/command for training?

### ISSUE THREAD

**Issue by asmith26** [vimalabs/VIMA#25]
Hi there, 

I've managed to successfully run the [demo](https://github.com/vimalabs/VIMA#demo), and am interested in learning more about the training. Is there any scripts/commands etc. that I can use to run the training?

Many thanks for any help, and for this amazing work! :)

**Comment by yunfanjiang** [comment]
Thank you for your interest in our work. Since training code depends on internal codebase and unfortunately we cannot release at this time. That being said, I can still share that we built our pipeline based on [PyTorch Lightning](https://www.pytorchlightning.ai/index.html) with DDP (distributed data parallel) for acceleration.

**Comment by asmith26** [comment]
Thanks for the info. If you are able to share anything like pseudo-code of the training algorithm, that would be very helpful.

Many thanks again
