### ISSUE TITLE
Question of the object encoding and training details

### ISSUE THREAD

**Issue by JisuHann** [vimalabs/VIMA#35]
Hi, I have some questions regarding the code
1. Is there a specific reason to fuse the end effector features with the object features ([this line](https://github.com/vimalabs/VIMA/blob/4758671789ce2b8e94181f917bc3dd948e866fe7/vima/policy/vima_policy.py#L256C31-L256C31))? Is there any intuition of this fusion?
2. Can I know how much training epochs/time have been used? I checked you used 8 V100 GPUs.

Thank you so much in advance.
(2023.09.21) I resolved some questions and updated ones. (You can ignore the mail that I send to you directly)

**Comment by yunfanjiang** [comment]
Hi Jisu,

Thank you for your interest in our work. To answer your questions:

> Is there a specific reason to fuse the end effector features with the object features ([this line](https://github.com/vimalabs/VIMA/blob/4758671789ce2b8e94181f917bc3dd948e866fe7/vima/policy/vima_policy.py#L256C31-L256C31))? Is there any intuition of this fusion?

State of the end effector indeed constitutes part of observation feature. Although in the current version due to the usage of primitive actions, end effector state should remain constant (e.g., the gripper is always open before and after pick & place). Once we go to lower level of action space (e.g., pose of the end effector and open/close the gripper), ee states are necessary to provide sufficient information to the model.

> Can I know how much training epochs/time have been used? I checked you used 8 V100 GPUs.

Training the most computationally heavy model took about one day. We trained for 10 epochs and selected model ckpt based on prediction accuracy on a held-out val set.
